@server = http://localhost:4004

## Bulk API for TT02

### ------------------------------------------------------------------------
# POST {{server}}/PostNumberTileDynamic
GET  {{server}}/odata/v4/catalog-fruttarolo/clearFruttarolo()
# Authorization: Bearer {{tokenValue}}
Content-Type: application/json




